apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portail-formation-cert
  labels:
    app: portail-formation
spec:
  commonName: "portail-formation.school-by-hiit.fr"
  secretName: portail-formation-cert
  dnsNames:
    - "portail-formation.school-by-hiit.fr"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer