apiVersion: v1
kind: ServiceAccount
metadata:
    name: portail-formation

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: portail-formation
rules:
    - apiGroups:
          - ""
      resources:
          - secrets
      resourceNames:
          - "portail-formation-cert"
      verbs:
          - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: portail-formation
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: portail-formation
subjects:
    - kind: ServiceAccount
      name: portail-formation